name: Test

on:
  push:

jobs:
  test:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/openkim/developer-platform:latest-minimal
        options: --user root
      defaults:
        run: 
            shell: bash
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Test EquilibriumCrystalStructure property validation
          run: |
            cd tests
            pip install pytest
            pytest -rA