name: Test

on:
  push:

jobs:
  test:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/openkim/developer-platform:latest-minimal
        volumes:
          - tests:/home/openkim/tests
      steps:
        - name: Test EquilibriumCrystalStructure property validation
          run: |
             pip install pytest
             cd tests
             pytest